### ISSUE TITLE
Panel has a NAVCOM radio but no CDI for the NAV

### ISSUE THREAD

**Issue by davidmegginson** [TheFGFSEagle/c140-family#1]
You can tune in a VOR or LOC, but you can't do anything with it. I recommend either

1. Adding a CDI to the panel (assuming an owner upgraded in the 1970s), or 
2. Switching to a COM-only radio.

**Comment by magnetic-eagle** [comment]
Looks like this has been done by D-ECHO meanwhile - so closing this.
